name: chembounce
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core Python version
  - python=3.8
  
  # Core computational chemistry libraries with specific versions
  - rdkit=2020.09.5
  - numpy>=1.24,<2.0
  - pandas>=2.0,<3.0
  - scipy>=1.10,<2.0
  - scikit-learn>=1.3,<2.0
  
  # Visualization
  - matplotlib>=3.7,<4.0
  
  # Jupyter support
  - ipykernel
  - ipython
  - jupyter_client
  
  # Basic utilities
  - pip
  - setuptools
  - wheel
  
  # Install remaining packages via pip
  - pip:
    # Molecular chemistry tools
    - molvs==0.1.1
    - oddt==0.7
    - pubchempy==1.0.4
    - scaffoldgraph==1.1.2
    
    # Utilities
    - networkx>=3.0
    - joblib>=1.3
    - requests>=2.31
    - tabulate>=0.9
    
    # Additional dependencies
    - pillow>=10.0
    - python-dateutil>=2.8